=== Rintel/Schiffe-Quiz/xml/portraits_schema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com/Portraits"
            xmlns:p="http://example.com/Portraits" elementFormDefault="qualified">
    <xsd:element name="gallery">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="painting" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="title" type="xsd:string"/>
                            <xsd:element name="description" type="xsd:string"/>
                            <xsd:element name="actor" type="p:actorComplex"/>
                            <xsd:element name="date" type="p:dateComplex"/>
                            <xsd:element name="materials_techniques" type="p:materials_techniquesComplex"/>
                            <xsd:element name="resourceLink" type="xsd:anyURI"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="actorComplex">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="birthYear" type="p:year"/>
            <xsd:element name="deathYear" type="p:year"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="dateComplex">
        <xsd:sequence>
            <xsd:element name="earliestDate" type="p:year"/>
            <xsd:element name="latestDate" type="p:year"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="materials_techniquesComplex">
        <xsd:sequence>
            <xsd:element name="material" type="xsd:string" minOccurs="0"
                         maxOccurs="unbounded"/>
            <xsd:element name="technique" type="xsd:string" minOccurs="0"
                         maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="year">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([0-9]{4})?"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Rintel/Schiffe-Quiz/xml/portraits_transformed.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:gallery xsi:schemaLocation="http://example.com/Portraits portraits_schema.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:p="http://example.com/Portraits">
    <p:painting>
        <p:title>Schnaubrigg WILHELM</p:title>
        <p:description>
            Schiff von Backbordseite gezeigt, mit allen Segeln vor dem Wind auf
            Steuerbordbug fahrend. Groß- und Briggsegel sind teilweise aufgegeit.
            Flaggen: Dannebrog mit Zirkel „FR VI“ und Krone, Kriegswimpel Dänemarks.
            Als Galionsfigur ein schreitender Mann mit einem Brief in der Hand.
            10 Leute sind an Deck.
            Im Hintergrund links Helgoland und kleineres Segelfahrzeug, rechts ein Kutter mit dänischem
            Kriegswimpel und zwei Pfahlewer.
        </p:description>
        <p:actor>
            <p:name>Schwartze, G. M.</p:name>
            <p:birthYear/>
            <p:deathYear/>
        </p:actor>
        <p:date>
            <p:earliestDate>1817</p:earliestDate>
            <p:latestDate>1817</p:latestDate>
        </p:date>
        <p:materials_techniques>
            <p:material>Büttenpapier</p:material>
            <p:technique>Federzeichnung</p:technique>
            <p:technique>Aquarell</p:technique>
            <p:technique>Gouache</p:technique>
        </p:materials_techniques>
        <p:resourceLink>
            http://resources.digicult-museen.net/dam/provided_image/m57d82520ab637
        </p:resourceLink>
    </p:painting>
    <p:painting>
        <p:title>Brigg CATHARINA</p:title>
        <p:description>
            Das Schiff wird von Backbord vorn in Orkansituation gezeigt. Klüver,
            Groß- und Großmarssegel sind zerfetzt, die Royalsegel sind aufgetucht, das
            Focksegel ist aufgegeit, und das schon beschädigte Vormarssegel wird gerade aufgegeit.
            7 Personen auf dem Schiff, davon 2 in den Wanten und 2 in den Rahen.
        </p:description>
        <p:actor>
            <p:name>Truelsen, Nis Nissen</p:name>
            <p:birthYear>1792</p:birthYear>
            <p:deathYear>1862</p:deathYear>
        </p:actor>
        <p:date>
            <p:earliestDate>1854</p:earliestDate>
            <p:latestDate>1859</p:latestDate>
        </p:date>
        <p:materials_techniques>
            <p:material>Büttenpapier</p:material>
            <p:technique>Federzeichnung</p:technique>
            <p:technique>Aquarell</p:technique>
            <p:technique>Gouache</p:technique>
        </p:materials_techniques>
        <p:resourceLink>
            http://resources.digicult-museen.net/dam/provided_image/m57d825218aee2
        </p:resourceLink>
    </p:painting>
    <p:painting>
        <p:title>Brigg ANNA MARIA</p:title>
        <p:description>
            Schiff von Backbordseite gezeigt, unter allen Segeln einschließlich
            der Leesegel mit Backstagsbrise vor dem Wind laufend.
            Geführt wird der Dannebrog mit Zirkel „FR VI“, ein weißer Wimpel mit
            gelbem Rand und den dänischen Farben mit Zirkel sowie die Dreyersche Reedereiflagge.
            Auf dem Schiff sind Leute. Im Hintergrund links ein Blankeneser Pfahlewer, rechts Helgoland.
        </p:description>
        <p:actor>
            <p:name>Böttger, Jacob Ahrend Hinrich</p:name>
            <p:birthYear>1781</p:birthYear>
            <p:deathYear>1860</p:deathYear>
        </p:actor>
        <p:date>
            <p:earliestDate>1831</p:earliestDate>
            <p:latestDate>1831</p:latestDate>
        </p:date>
        <p:materials_techniques>
            <p:material>Papier</p:material>
            <p:material>Grafitstift</p:material>
            <p:technique>Federzeichnung</p:technique>
            <p:technique>Aquarell</p:technique>
        </p:materials_techniques>
        <p:resourceLink>
            http://resources.digicult-museen.net/dam/provided_image/m57d825220573b
        </p:resourceLink>
    </p:painting>
    <p:painting>
        <p:title>Brigg THEODOR</p:title>
        <p:description>
            Schiff von Steuerbordseite dargestellt, in Vorbereitung des Ankermanövers.
            Bram- und Marsrahen werden gefiert und die Segel aufgegeit, die Gaffel des Briggsegels wird
            ebenfalls gefiert. Die Vorsegel sind gefallen.
            Flaggen: Dannebrog mit Zirkel „FR VI“ sowie im Vortopp eine blaue (wie auch
            die dänische Flagge hell und dunkel gestreift dargestellte) Flagge mit einem mittigen
            weißen Karree, möglicherweise die Reedereiflagge.
            Auf dem Schiff sind 12 Mann, teilweise mit den Segelmanövern beschäftigt. Links
            Leuchtturm und Mole von St. Thomas, rechts ein englischer Kriegskutter.
            Das Schiff wurde noch im 18. Jh. erbaut.
        </p:description>
        <p:actor>
            <p:name>unbekannt</p:name>
            <p:birthYear/>
            <p:deathYear/>
        </p:actor>
        <p:date>
            <p:earliestDate>1808</p:earliestDate>
            <p:latestDate>1808</p:latestDate>
        </p:date>
        <p:materials_techniques>
            <p:material>Papier</p:material>
            <p:technique>Federzeichnung</p:technique>
            <p:technique>Aquarell</p:technique>
        </p:materials_techniques>
        <p:resourceLink>
            http://resources.digicult-museen.net/dam/provided_image/m57d82522669eb
        </p:resourceLink>
    </p:painting>
    <p:painting>
        <p:title>Fregatte AEOLUS</p:title>
        <p:description>
            Schiff von Backbordseite gezeigt, unter Vorstengestag-, gerefftem
            Fock-und gerefftem Besansegel am Winde fahrend.
            An der Gaffel der Dannebrog mit Zirkel „C 7“ und Krone.
            9 Personen an Deck, die verschiedene Arbeiten ausführen, die wegen des starken Windes,
            ablesbar an der Besegelung und am dunklen Himmel, notwendig sind. Auf dem Vorschiff werden
            Leinen klariert. Bei den an Deck liegenden Booten werden die Laschings nachgezogen. Vom Heck
            hängt eine Jakobsleiter bis auf die Wasseroberfläche (eine damals übliche Präventivmaßnahme
            zur Rettung über Bord Gespülter).
            Links im Hintergrund gebirgige Insel, bezeichnet „CANDIA“ (= Kreta). Rechts im
            Hintergrund dasselbe Schiff noch einmal bei starkem Wind beiliegend mit gefierten
            Bramstengen.
        </p:description>
        <p:actor>
            <p:name>unbekannt</p:name>
            <p:birthYear/>
            <p:deathYear/>
        </p:actor>
        <p:date>
            <p:earliestDate/>
            <p:latestDate/>
        </p:date>
        <p:materials_techniques>
            <p:material>Büttenpapier</p:material>
            <p:technique>Federzeichnung</p:technique>
            <p:technique>Aquarell</p:technique>
        </p:materials_techniques>
        <p:resourceLink>
            http://resources.digicult-museen.net/dam/provided_image/m57d82522ec2c3
        </p:resourceLink>
    </p:painting>
    <p:painting>
        <p:title>Fregatte AMPHITRITE</p:title>
        <p:description>
            Schiff von Steuerbordseite gezeigt, unter allen Segeln am Winde auf
            Backbordbug segelnd; nur die Royals sind festgemacht.
            An der Gaffel der Dannebrog mit Zirkel „C 7“ und Krone, im Kreuz- und im
            Vortopp rote Wimpel, im Großtopp der dänische Kriegswimpel. 12 Stückpforten
            mit Kanonen an der Steuerbordseite.
            12 Personen an Deck.
            Im Hintergrund links und rechts am Horizont 4 weitere Schiffe, 3 Briggs und 1 Vollschiff.
        </p:description>
        <p:actor>
            <p:name>Böttger, Jacob Ahrend Hinrich</p:name>
            <p:birthYear>1781</p:birthYear>
            <p:deathYear>1860</p:deathYear>
        </p:actor>
        <p:date>
            <p:earliestDate>1806</p:earliestDate>
            <p:latestDate>1806</p:latestDate>
        </p:date>
        <p:materials_techniques>
            <p:material>Büttenpapier</p:material>
            <p:technique>Federzeichnung</p:technique>
            <p:technique>Aquarell</p:technique>
        </p:materials_techniques>
        <p:resourceLink>
            http://resources.digicult-museen.net/dam/provided_image/m57d825235bab2
        </p:resourceLink>
    </p:painting>
    <p:painting>
        <p:title>Schnaubrigg MELONA vor Riga</p:title>
        <p:description>
            Das Schiff wird von Backbordseite an der Flußbrücke der Düna
            vor Anker liegend dargestellt. Alle Segel sind festgemacht.
            Flaggen: englische Handelsflagge an der Gaffel, Namenswimpel im Großtopp,
            Reedereiflagge im Vortopp, englische Lotsenflagge am Klüver.
            15 Personen an Deck, davon eine Frau. Drei Personen beschäftigen sich mit dem Beladen.
            Im Hintergrund die Vedute der Stadt Riga.
            Im Gegensatz zu den üblichen Schiffsporträts wird hier neben einer vollständigen
            Hafenszene mit Stadtansicht und Treiben auf dem Kai und an der Brücke auch das
            Beladen des Schiffes gezeigt.
        </p:description>
        <p:actor>
            <p:name>Shlei (Slie), Carl Gustav</p:name>
            <p:birthYear/>
            <p:deathYear/>
        </p:actor>
        <p:date>
            <p:earliestDate>1826</p:earliestDate>
            <p:latestDate>1826</p:latestDate>
        </p:date>
        <p:materials_techniques>
            <p:material>Papier</p:material>
            <p:technique>Federzeichnung</p:technique>
            <p:technique>Aquarell</p:technique>
        </p:materials_techniques>
        <p:resourceLink>
            http://resources.digicult-museen.net/dam/provided_image/m57d82523d5894
        </p:resourceLink>
    </p:painting>
    <p:painting>
        <p:title>Fregatte VARIABLE</p:title>
        <p:description>
            Schiff von Backbord achtern gesehen, vor dem Wind auf die Reede von
